server:
  port: 8060
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka
 
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: olxadvertises-service
        uri: lb://olxadvertises-service
        predicates:
        - Path=/olxadvertises/**
        filters:
        - RewritePath=/olxadvertises-service/(?<path>.*), /$\{path}
        
springdoc:
  swagger-ui:
    urls:
      - name: employee
        url: /v3/api-docs/employee